### PR TITLE
T17 seo optimization

### LINKED ISSUE #17: Create sitemap.xml for SEO
Generate sitemap.xml and update robots.txt to improve SEO

### PR DESCRIPTION
**Pull request by kilahimm**
Adds rake task for running sitemap generation
Updates robots.txt to reference sitemap.xml
Configures Sitemap gem.

Resolves #17

### CODE REVIEW

**Comment by kilahimm** [comment]
[Generate site-maps to support Google indexing](https://trello.com/c/rrJcvqNm/247-generate-site-maps-to-support-google-indexing)

**Comment by kerchner** [comment]
@kilahimm @StudioZut This needs to be reopened.  `Gemfile.lock` should also be part of the branch/pull request.

**Comment by kilahimm** [comment]
@kerchner doesn't `Gemfile` entries build the `Gemfile.lock` when you run `bundle install` ?  This  passes Travis on the https://github.com/gwu-libraries/scholarspace/pull/240 without the `Gemfile.lock` update.

**Comment by kerchner** [comment]
@kilahimm If it sees Gemfile.lock, it will first try to install the exact versions specified in Gemfile.lock.   This is how we can ensure that we (and our deployments) are all running the exact same set of gem versions.

So for example, if at the time you create this branch and install the `sitemap` gem, sitemap is at 0.3.3, then you want to make sure that when you deploy a week later and bundle install, your deployment doesn't end up with some new version 0.4.0 that just came out.

While we could pin the version of `sitemap` in `Gemfile`, the problem there is that the `sitemap` gem has its own dependencies.  `Gemfile.lock` will pin the versions of not only the gem but all of its dependencies.

Hence the best practice of including `Gemfile.lock` as part of the version-controlled code base.

**Pull request merged**
