### PR TITLE
Added nohup alternative for solr/jetty

### PR DESCRIPTION
**Pull request by StudioZut**

### CODE REVIEW

**Comment by kerchner** [comment]
@StudioZut I'd prefer not to get too too explicit about things like `> output.log 2>&1` leaving that instead to developer discretion.  Your thoughts?

**Comment by StudioZut** [comment]
@kerchner I think you're right, especially if we're about to change the way we're going to connect to solr/fedora on dev anyway

**Comment by kerchner** [comment]
So... do we kill this PR then?

**Comment by StudioZut** [comment]
I think so

**Comment by kerchner** [comment]
PR not needed.

**Pull request closed without merging**
